version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/contactsdb
    volumes:
      - .:/usr/src/app
    command: npm start
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: